"""Generate README.md from profile.json.

Every section is a <picture>: desktop art for wide screens, mobile art
(bigger type, stacked layouts) for phones. The desktop <source> comes first,
so if a renderer ignores the media queries it still shows the desktop art.
"""
import re

from kit import CFG, ROOT

USER = CFG["github_user"]
RAW = f"https://raw.githubusercontent.com/{USER}/{CFG.get('profile_repo', USER)}/{CFG.get('branch', 'main')}"


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def picture(name, alt, href=None):
    pic = (f'<picture>'
           f'<source media="(min-width: 701px)" srcset="{RAW}/assets/desktop/{name}">'
           f'<source media="(max-width: 700px)" srcset="{RAW}/assets/mobile/{name}">'
           f'<img src="./assets/desktop/{name}" alt="{alt}">'
           f'</picture>')
    return f'<a href="{href}">{pic}</a>' if href else pic


def build():
    email, site, li = CFG["email"], CFG["portfolio"], CFG.get("linkedin")
    spot = CFG["spotlight"]
    gh = f"https://github.com/{USER}"
    projects = "\n".join(picture(f"items/project-{slug(n)}.svg", f"{n} — {d} ({u.replace('https://', '')})", u)
                         for n, d, u, _ in CFG["projects"])
    repos = "\n".join(picture(f"items/repo-{slug(n)}.svg", f"{n} — {d}", f"{gh}/{n}") for n, d in CFG["repos"])
    links = "\n".join(picture(f"items/link-{slug(label)}.svg", label, url) for label, url in CFG["links"])
    text_links = " · ".join(filter(None, [
        f'<a href="mailto:{email}">{email}</a>',
        f'<a href="{site}">{site.replace("https://", "")}</a>',
        f'<a href="{li}">linkedin</a>' if li else "",
    ]))
    sections = [
        picture("hero.svg", f"{CFG['full_name']} — building {', '.join(CFG['roles'])}. Open to work.", site),
        picture("tldr.svg", "Why shortlist Tushar: ships end to end, builds hard systems, shows up every day, owns the whole stack.",
                f"mailto:{email}"),
        picture("skyline.svg", "Contribution graph for the last year that tilts into a 3D skyline", gh),
        picture("whoami.svg", "ASCII portrait and live contribution stats", site),
        picture("spotlight.svg", f"{spot['name']} architecture: " + " → ".join(p[0] for p in spot["pipeline"])
                + ", with automated retraining", f"{gh}/{spot['repo']}"),
        picture("stack.svg", "Tech stack: " + ", ".join(i for _, items in CFG["stack"] for i in items),
                f"{gh}?tab=repositories"),
        picture("langs.svg", "Languages across all public repositories", f"{gh}?tab=repositories"),
        picture("activity.svg", "Recent public activity", gh),
        picture("head-live.svg", "ls ~/live --deployed", site) + "\n" + projects,
        picture("head-repos.svg", "ls ~/repos --featured", f"{gh}?tab=repositories") + "\n" + repos,
        picture("head-links.svg", "./contact.sh", f"mailto:{email}") + "\n" + links,
        picture("footer.svg", "Thanks for scrolling — if you're hiring, let's build something real.", f"mailto:{email}"),
    ]
    body = "\n<br><br>\n".join(sections)
    return f"""<!-- Generated by scripts/make_readme.py from profile.json — edit that file, not this one. -->
<div align="center">

{body}

<br>

<sub>{text_links}</sub>
<br>
<sub>every panel above is an SVG generated by <a href="./scripts">./scripts</a> and refreshed daily by GitHub Actions</sub>

</div>
"""


def main():
    (ROOT / "README.md").write_text(build(), encoding="utf-8")
    print("wrote README.md")


if __name__ == "__main__":
    main()
